project: 
  type: website
  output-dir: docs

website:
  title: "MUhammad Nasir Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "CDC Data Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Fitting Models Exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "Machine-learning 1 Exercise"
            file: fml-models-exercise.qmd

    right:
      - icon: github 
        href: https://github.com/nasir27712/muhammadnasir-mada2025-portopolio      
format:
  html:
    theme: sandstone
    highlight: zenburn
    css: styles.css
    toc: FALSE